# Generated by Django 3.2.1 on 2021-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidenteVehicular',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('claseAC', models.CharField(choices=[('A', 'Automovil'), ('B', 'Omnibus'), ('C', 'Camion'), ('D', 'Motocicleta'), ('E', 'Atropellado')], default=None, max_length=10)),
                ('cantVehiculos', models.IntegerField()),
                ('cantPersonas', models.IntegerField()),
                ('corteTransito', models.BooleanField()),
                ('tipoCalle', models.CharField(choices=[('C', 'Calle'), ('A', 'Acenida'), ('R', 'Ruta'), ('U', 'Undefined')], default='U', max_length=10)),
                ('herido', models.CharField(max_length=20)),
                ('servEmergencia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Accidente Vehicular',
                'verbose_name_plural': 'Accidentes Vehiculares',
            },
        ),
        migrations.CreateModel(
            name='IncendioBaldio',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('entreCalles', models.CharField(max_length=30)),
                ('riesgoProp', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Incendio de Baldio',
                'verbose_name_plural': 'Incendios de Baldios',
            },
        ),
        migrations.CreateModel(
            name='IncendioElectrico',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('desperfecto', models.CharField(max_length=30)),
                ('humoLlamas', models.CharField(max_length=30)),
                ('epec', models.CharField(max_length=30)),
                ('servEmergencia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Incendio Electrico',
                'verbose_name_plural': 'Incendios Electricos',
            },
        ),
        migrations.CreateModel(
            name='IncendioForestal',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('sentido', models.CharField(max_length=15)),
                ('riesgoProp', models.BooleanField()),
                ('edificios', models.IntegerField()),
                ('servEmergencia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Incendio Forestal',
                'verbose_name_plural': 'Incendios Forestales',
            },
        ),
        migrations.CreateModel(
            name='IncendioVehicular',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('tipoVehiculo', models.CharField(max_length=20)),
                ('humoLlamas', models.CharField(max_length=30)),
                ('localOcup', models.BooleanField()),
                ('gnc', models.CharField(max_length=20)),
                ('riesgoProp', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Incendio Vehicular',
                'verbose_name_plural': 'Incendios Vehiculares',
            },
        ),
        migrations.CreateModel(
            name='IncendioVivienda',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('entreCalles', models.CharField(max_length=30)),
                ('estadoFuego', models.CharField(max_length=30)),
                ('habitantes', models.CharField(max_length=20)),
                ('localHabit', models.CharField(max_length=40)),
                ('descVivienda', models.CharField(max_length=50)),
                ('espera', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Incendio de Vivienda',
                'verbose_name_plural': 'Incendios de Viviendas',
            },
        ),
        migrations.CreateModel(
            name='RescateAnimal',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('animal', models.CharField(max_length=15)),
                ('condicionAnimal', models.CharField(max_length=30)),
                ('vision', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Rescate Animal',
                'verbose_name_plural': 'Rescate de Animales',
            },
        ),
        migrations.CreateModel(
            name='RescateCadaver',
            fields=[
                ('idAlarma', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('receptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('referencia', models.TextField(max_length=100)),
                ('esPolicia', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Rescate de Cadaver',
                'verbose_name_plural': 'Rescates de Cadaveres',
            },
        ),
    ]
