# Generated by Django 3.2.1 on 2021-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentevehicular',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='accidentevehicular',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accidentevehicular',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incendiobaldio',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='incendiobaldio',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incendiobaldio',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incendioelectrico',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='incendioelectrico',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incendioelectrico',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incendioforestal',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='incendioforestal',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incendioforestal',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incendiovehicular',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='incendiovehicular',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incendiovehicular',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incendiovivienda',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='incendiovivienda',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incendiovivienda',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rescateanimal',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rescateanimal',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rescateanimal',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rescatecadaver',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rescatecadaver',
            name='idAlarma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rescatecadaver',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
