# Generated by Django 3.2.1 on 2021-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0002_auto_20210914_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentevehicular',
            name='cantVehiculos',
            field=models.CharField(max_length=200),
        ),
    ]
