# Generated by Django 3.2.1 on 2021-08-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0002_auto_20210823_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incendiovehicular',
            old_name='localOcup',
            new_name='vehiculoOcup',
        ),
    ]
