# Generated by Django 3.2.1 on 2021-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0003_rename_localocup_incendiovehicular_vehiculoocup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentevehicular',
            name='tipoCalle',
            field=models.CharField(choices=[('C', 'Calle'), ('A', 'Avenida'), ('R', 'Ruta'), ('U', 'Undefined')], default='U', max_length=10),
        ),
    ]
