# Generated by Django 3.2.1 on 2021-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0004_alter_accidentevehicular_tipocalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aux', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Formulario Auxiliar',
                'verbose_name_plural': 'Formularios Auxiliares',
            },
        ),
    ]
