# Generated by Django 3.2.1 on 2021-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0004_alter_accidentevehicular_cantvehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentevehicular',
            name='cantVehiculos',
            field=models.CharField(default='defaul', max_length=200),
            preserve_default=False,
        ),
    ]
