# Generated by Django 3.2.1 on 2021-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0005_formularioauxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioauxiliar',
            name='Aux',
            field=models.TextField(max_length=35, null=True),
        ),
    ]
