# Generated by Django 3.2.1 on 2021-08-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0006_alter_formularioauxiliar_aux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioauxiliar',
            old_name='Aux',
            new_name='aux',
        ),
    ]
