# Generated by Django 3.2.1 on 2021-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0007_rename_aux_formularioauxiliar_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioauxiliar',
            name='aux',
            field=models.TextField(default='Aca debería haber algo'),
        ),
    ]
