# Generated by Django 3.2.1 on 2021-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusBV', '0008_alter_formularioauxiliar_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioauxiliar',
            name='aux',
            field=models.TextField(default='Formulario Auxiliar'),
        ),
    ]
